# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Administrator/Desktop/mac_ip/project_2/project_2.srcs/sources_1/ip/ten_gig_eth_mac_0/ten_gig_eth_mac_0.xci
# IP: The module: 'ten_gig_eth_mac_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/mac_ip/project_2/project_2.srcs/sources_1/ip/ten_gig_eth_mac_0/synth/ten_gig_eth_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ten_gig_eth_mac_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/mac_ip/project_2/project_2.srcs/sources_1/ip/ten_gig_eth_mac_0/synth/ten_gig_eth_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ten_gig_eth_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/mac_ip/project_2/project_2.srcs/sources_1/ip/ten_gig_eth_mac_0/synth/ten_gig_eth_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ten_gig_eth_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Administrator/Desktop/mac_ip/project_2/project_2.srcs/sources_1/ip/ten_gig_eth_mac_0/ten_gig_eth_mac_0.xci
# IP: The module: 'ten_gig_eth_mac_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/mac_ip/project_2/project_2.srcs/sources_1/ip/ten_gig_eth_mac_0/synth/ten_gig_eth_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ten_gig_eth_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/mac_ip/project_2/project_2.srcs/sources_1/ip/ten_gig_eth_mac_0/synth/ten_gig_eth_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ten_gig_eth_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/mac_ip/project_2/project_2.srcs/sources_1/ip/ten_gig_eth_mac_0/synth/ten_gig_eth_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ten_gig_eth_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
